repos:
  - repo: https://github.com/LiquidFun/aoc_tiles
    rev: 0.6.2
    hooks:
      - id: aoc-tiles
        args:
          - --overwrite-year=2024
          - -exclude-patterns=aoc2024/src/meta/*,aoc2024/src/objects/*